version: 2.1
resource_types:
  - name: docker-hub
    type: docker-image
    privileged: true
    source:
      repository: concourse/docker-image-resource
    defaults:
      email: {{docker-hub-email}}
      username: {{docker-hub-user}}
      password: {{docker-hub-password}}

resources:
  # Code repository - one entry per buildable to avoid building everything when we change anything
  - name: php-7.2-code
    type: git
    check_every: 5m
    source:
      uri: https://github.com/phpdocker-io/base-images.git
      branch: master
      paths:
        - php/7.2/*/**

  - name: php-7.3-code
    type: git
    check_every: 5m
    source:
      uri: https://github.com/phpdocker-io/base-images.git
      branch: master
      paths:
        - php/7.3/*/**

  - name: php-7.4-code
    type: git
    check_every: 5m
    source:
      uri: https://github.com/phpdocker-io/base-images.git
      branch: master
      paths:
        - php/7.4/*/**

  - name: php-8.0-code
    type: git
    check_every: 5m
    source:
      uri: https://github.com/phpdocker-io/base-images.git
      branch: master
      paths:
        - php/8.0/*/**

  - name: nginx-pagespeed-code
    type: git
    check_every: 5m
    source:
      uri: https://github.com/phpdocker-io/base-images.git
      branch: master
      paths:
        - nginx-pagespeed/*


  # Periodic triggers to get daily builds
  - name: time-slot-1
    type: time
    source:
      start: 12:00 AM
      stop: 12:20 AM

  - name: time-slot-2
    type: time
    source:
      start: 12:25 AM
      stop: 12:45 AM

  - name: time-slot-3
    type: time
    source:
      start: 12:50 AM
      stop: 1:10 AM

  - name: time-slot-4
    type: time
    source:
      start: 1:20 AM
      stop: 1:50 AM

  # Docker hub repositories
  - name: php72-cli
    type: docker-hub
    source:
      repository: phpdockerio/php72-cli

  - name: php72-fpm
    type: docker-hub
    source:
      repository: phpdockerio/php72-fpm

  - name: php73-cli
    type: docker-hub
    source:
      repository: phpdockerio/php73-cli

  - name: php73-fpm
    type: docker-hub
    source:
      repository: phpdockerio/php73-fpm

  - name: php74-cli
    type: docker-hub
    source:
      repository: phpdockerio/php74-cli

  - name: php74-fpm
    type: docker-hub
    source:
      repository: phpdockerio/php74-fpm

  - name: php74-swoole
    type: docker-hub
    source:
      repository: phpdockerio/php74-swoole

  - name: php80-cli
    type: docker-hub
    source:
      repository: phpdockerio/php80-cli

  - name: php80-fpm
    type: docker-hub
    source:
      repository: phpdockerio/php80-fpm

  - name: php80-swoole
    type: docker-hub
    source:
      repository: phpdockerio/php80-swoole

  - name: nginx-pagespeed
    type: docker-hub
    source:
      repository: phpdockerio/nginx-pagespeed

jobs:
  - name: php-7.2
    public: true
    plan:
      - get: php-7.2-code
        trigger: true
      - get: time-slot-3
        trigger: true
      - put: php72-cli
        params:
          build: php-7.2-code/php/7.2/cli
      - put: php72-fpm
        params:
          build: php-7.2-code/php/7.2/fpm

  - name: php-7.3
    public: true
    plan:
      - get: php-7.3-code
        trigger: true
      - get: time-slot-3
        trigger: true
      - put: php73-cli
        params:
          build: php-7.3-code/php/7.3/cli
      - put: php73-fpm
        params:
          build: php-7.3-code/php/7.3/fpm

  - name: php-7.4
    public: true
    plan:
      - get: php-7.4-code
        trigger: true
      - get: time-slot-2
        trigger: true
      - put: php74-cli
        params:
          build: php-7.4-code/php/7.4/cli
      - put: php74-fpm
        params:
          build: php-7.4-code/php/7.4/fpm
      - put: php74-swoole
        params:
          build: php-7.4-code/php/7.4/swoole

  - name: php-8.0
    public: true
    plan:
      - get: php-8.0-code
        trigger: true
      - get: time-slot-1
        trigger: true
      - put: php80-cli
        params:
          build: php-8.0-code/php/8.0/cli
      - put: php80-fpm
        params:
          build: php-8.0-code/php/8.0/fpm
      - put: php80-swoole
        params:
          build: php-8.0-code/php/8.0/swoole

  - name: nginx-pagespeed
    public: true
    plan:
      - get: nginx-pagespeed-code
        trigger: true
      - get: time-slot-4
        trigger: true
      - put: nginx-pagespeed
        params:
          build: nginx-pagespeed-code/nginx-pagespeed
